#include "common.h"
#include "sys/math3d.h"

/*
 * 0x11FE80..0x1204B8 of the vector / matrix library (config/symbols/vu0_a.txt): screen-range tests, the sine / cosine
 * helper, and the matrix routines on matrices in memory. Everything here is hand-written VU0 (or 128-bit) assembly
 * in the original except Mtx_AxisZToEuler, and is kept as top-level assembly (same bytes, checked by fdiff).
 * What each routine computes, operation by operation, is written out in C in src/port/vu0_a.c (bt3-port repository).
 *
 * Registers the routines rely on: vf0 = (0,0,0,1) (hard-wired), vf1 = (0,0,1,0), vf2 = (0,1,0,0), vf3 = (1,0,0,0)
 * (Vu0_InitAxisRegs at boot).
 */

extern void Mtx_MulVec4(Vec4 *dst, Mtx44 *m, Vec4 *v);
extern void Vec3_DirToEuler(Vec4 *out, Vec4 *dir);

/* (0, 0, 1, 1). */
extern Vec4 gVu0AxisZW;

/* s32 IVec4_InGsRange(IVec4 *p): 1 when 0 < p.x / 16 < 4096, 0 < p.y / 16 < 4096 and p.w > 0 (sticky zero / sign flags
 * of p - 0 on x, y, w and of 4096 - p on x, y), else 0. sceVu0ClipScreen with integer input and the result inverted. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl IVec4_InGsRange\n"
    ".type IVec4_InGsRange, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "IVec4_InGsRange:\n"
    "    lqc2 $vf7, 0x0($4)\n"
    "    vsub.xyzw $vf4, $vf0, $vf0\n"
    "    lui $8, (0x45800000 >> 16)\n"
    "    dsll $8, $8, 16\n"
    "    ori $8, $8, 0x4580\n"
    "    dsll $8, $8, 16\n"
    "    qmtc2 $8, $vf5\n"
    "    vitof4.xy $vf7, $vf7\n"
    "    vitof0.zw $vf7, $vf7\n"
    "    .word 0x48C08000 /* ctc2.ni $zero, $vi16 */\n"
    "    vsub.xyw $vf0, $vf7, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf7\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    .word 0x48428000 /* cfc2.ni $v0, $vi16 */\n"
    "    andi $2, $2, 0xC0\n"
    "    jr $31\n"
    "    sltiu $2, $2, 0x1\n"
    ".set pop\n"
    ".size IVec4_InGsRange, . - IVec4_InGsRange\n"
);

/* s32 IVec4_InGsRange3(IVec4 *a, IVec4 *b, IVec4 *c): 1 when all three points pass the test above. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl IVec4_InGsRange3\n"
    ".type IVec4_InGsRange3, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "IVec4_InGsRange3:\n"
    "    lqc2 $vf7, 0x0($4)\n"
    "    lqc2 $vf8, 0x0($5)\n"
    "    lqc2 $vf9, 0x0($6)\n"
    "    vsub.xyzw $vf4, $vf0, $vf0\n"
    "    lui $8, (0x45800000 >> 16)\n"
    "    dsll $8, $8, 16\n"
    "    ori $8, $8, 0x4580\n"
    "    dsll $8, $8, 16\n"
    "    qmtc2 $8, $vf5\n"
    "    vitof4.xy $vf7, $vf7\n"
    "    vitof0.zw $vf7, $vf7\n"
    "    vitof4.xy $vf8, $vf8\n"
    "    vitof0.zw $vf8, $vf8\n"
    "    vitof4.xy $vf9, $vf9\n"
    "    vitof0.zw $vf9, $vf9\n"
    "    .word 0x48C08000 /* ctc2.ni $zero, $vi16 */\n"
    "    vsub.xyw $vf0, $vf7, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf7\n"
    "    vsub.xyw $vf0, $vf8, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf8\n"
    "    vsub.xyw $vf0, $vf9, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf9\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    .word 0x48428000 /* cfc2.ni $v0, $vi16 */\n"
    "    andi $2, $2, 0xC0\n"
    "    jr $31\n"
    "    sltiu $2, $2, 0x1\n"
    ".set pop\n"
    ".size IVec4_InGsRange3, . - IVec4_InGsRange3\n"
);

/* s32 IVec4_InGsRange4(IVec4 *a, IVec4 *b, IVec4 *c, IVec4 *d): meant for four points, but c is loaded twice and d
 * ($a3) is never read (original bug). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl IVec4_InGsRange4\n"
    ".type IVec4_InGsRange4, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "IVec4_InGsRange4:\n"
    "    lqc2 $vf7, 0x0($4)\n"
    "    lqc2 $vf8, 0x0($5)\n"
    "    lqc2 $vf9, 0x0($6)\n"
    "    lqc2 $vf10, 0x0($6)\n"
    "    vsub.xyzw $vf4, $vf0, $vf0\n"
    "    lui $8, (0x45800000 >> 16)\n"
    "    dsll $8, $8, 16\n"
    "    ori $8, $8, 0x4580\n"
    "    dsll $8, $8, 16\n"
    "    qmtc2 $8, $vf5\n"
    "    vitof4.xy $vf7, $vf7\n"
    "    vitof0.zw $vf7, $vf7\n"
    "    vitof4.xy $vf8, $vf8\n"
    "    vitof0.zw $vf8, $vf8\n"
    "    vitof4.xy $vf9, $vf9\n"
    "    vitof0.zw $vf9, $vf9\n"
    "    vitof4.xy $vf10, $vf10\n"
    "    vitof0.zw $vf10, $vf10\n"
    "    .word 0x48C08000 /* ctc2.ni $zero, $vi16 */\n"
    "    vsub.xyw $vf0, $vf7, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf7\n"
    "    vsub.xyw $vf0, $vf8, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf8\n"
    "    vsub.xyw $vf0, $vf9, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf9\n"
    "    vsub.xyw $vf0, $vf10, $vf4\n"
    "    vsub.xy $vf0, $vf5, $vf10\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    vnop\n"
    "    .word 0x48428000 /* cfc2.ni $v0, $vi16 */\n"
    "    andi $2, $2, 0xC0\n"
    "    jr $31\n"
    "    sltiu $2, $2, 0x1\n"
    ".set pop\n"
    ".size IVec4_InGsRange4, . - IVec4_InGsRange4\n"
);

/* Vu0_SinCos: internal, non-standard call. In: angle in $f12. Out: vf12.x = sin, vf12.y = cos, vf12.z = vf12.w = +/-0.
 * Clobbers $v0, $t0, $t1, $f0, $f12, vf4-vf7, Q; callers keep $ra in $a2. u = angle < 0 ? pi/2 + angle : pi/2 - angle;
 * cos = u + c3 u^3 + c5 u^5 + c7 u^7 + c9 u^9; sin = +/- vsqrt(1 - cos * cos), negative when angle < 0.
 * Correct for |angle| <= pi only. (libvu0's _sceVu0ecossin.) */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Vu0_SinCos\n"
    ".type Vu0_SinCos, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Vu0_SinCos:\n"
    "    lui $2, %hi(gVu0SinCoef)\n"
    "    addiu $2, $2, %lo(gVu0SinCoef)\n"
    "    mtc1 $0, $f0\n"
    "    c.lt.s $f12, $f0\n"
    "    lwc1 $f0, %gp_rel(gVu0HalfPi)($28)\n"
    "    bc1f 1f\n"
    "    nop\n"
    "    add.s $f12, $f0, $f12\n"
    "    j 2f\n"
    "    li $9, 1\n"
    "1:  sub.s $f12, $f0, $f12\n"
    "    move $9, $0\n"
    "2:  mfc1 $8, $f12\n"
    "    qmtc2 $8, $vf4\n"
    "    lqc2 $vf5, 0($2)\n"
    "    vmr32.w $vf4, $vf4\n"
    "    vaddx.x $vf12, $vf0, $vf4x\n"
    "    vmul.x $vf4, $vf4, $vf4\n"
    "    vmulx.yzw $vf12, $vf12, $vf0x\n"
    "    vmulw.xyzw $vf6, $vf5, $vf4w\n"
    "    vmulx.xyzw $vf6, $vf6, $vf4x\n"
    "    vmulx.xyz $vf6, $vf6, $vf4x\n"
    "    vaddw.x $vf12, $vf12, $vf6w\n"
    "    vmulx.xy $vf6, $vf6, $vf4x\n"
    "    vaddz.x $vf12, $vf12, $vf6z\n"
    "    vmulx.x $vf6, $vf6, $vf4x\n"
    "    vaddy.x $vf12, $vf12, $vf6y\n"
    "    vaddx.x $vf12, $vf12, $vf6x\n"
    "    vaddx.xy $vf12, $vf0, $vf12x\n"
    "    vmul.x $vf7, $vf12, $vf12\n"
    "    vsubx.w $vf7, $vf0, $vf7x\n"
    "    vsqrt $Q, $vf7w\n"
    "    vwaitq\n"
    "    bnez $9, 3f\n"
    "    vaddq.x $vf7, $vf0, $Q\n"
    "    b 4f\n"
    "    vaddx.x $vf12, $vf0, $vf7x\n"
    "3:  vsubx.x $vf12, $vf0, $vf7x\n"
    "4:  jr $31\n"
    "    nop\n"
    ".set pop\n"
    ".size Vu0_SinCos, . - Vu0_SinCos\n"
);

/* void Vu0_InitAxisRegs(void): vf1 = (0,0,1,0), vf2 = (0,1,0,0), vf3 = (1,0,0,0). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Vu0_InitAxisRegs\n"
    ".type Vu0_InitAxisRegs, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Vu0_InitAxisRegs:\n"
    "    vmr32.xyzw $vf1, $vf0\n"
    "    vmr32.xyzw $vf2, $vf1\n"
    "    jr $31\n"
    "    vmr32.xyzw $vf3, $vf2\n"
    ".set pop\n"
    ".size Vu0_InitAxisRegs, . - Vu0_InitAxisRegs\n"
);

/* void Mtx_StoreIdentity(Mtx44 *m): rows = vf3, vf2, vf1, vf0. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_StoreIdentity\n"
    ".type Mtx_StoreIdentity, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_StoreIdentity:\n"
    "    sqc2 $vf3, 0x0($4)\n"
    "    sqc2 $vf2, 0x10($4)\n"
    "    sqc2 $vf1, 0x20($4)\n"
    "    jr $31\n"
    "    sqc2 $vf0, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_StoreIdentity, . - Mtx_StoreIdentity\n"
);

/* void Mtx_StoreIdentityRot(Mtx44 *m): rows 0-2 = vf3, vf2, vf1; row 3 untouched. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_StoreIdentityRot\n"
    ".type Mtx_StoreIdentityRot, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_StoreIdentityRot:\n"
    "    sqc2 $vf3, 0x0($4)\n"
    "    sqc2 $vf2, 0x10($4)\n"
    "    jr $31\n"
    "    sqc2 $vf1, 0x20($4)\n"
    ".set pop\n"
    ".size Mtx_StoreIdentityRot, . - Mtx_StoreIdentityRot\n"
);

/* void Mtx_ClearTrans(Mtx44 *m): row 3 = (0, 0, 0, 1). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_ClearTrans\n"
    ".type Mtx_ClearTrans, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_ClearTrans:\n"
    "    jr $31\n"
    "    sqc2 $vf0, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_ClearTrans, . - Mtx_ClearTrans\n"
);

/* void Mtx_GetTrans(Vec4 *v, Mtx44 *m): v = row 3 (128-bit move). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_GetTrans\n"
    ".type Mtx_GetTrans, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_GetTrans:\n"
    "    lq $8, 0x30($5)\n"
    "    jr $31\n"
    "    sq $8, 0x0($4)\n"
    ".set pop\n"
    ".size Mtx_GetTrans, . - Mtx_GetTrans\n"
);

/* angles = the pitch (x) and yaw (y) of the matrix's Z axis: Vec3_DirToEuler of (rows 0-2 of m, row 3 = (0,0,0,1))
 * times (0, 0, 1, 1), i.e. of row 2 with 1 added to its w. angles.z = 0. Compiled C with inline assembly. */
void Mtx_AxisZToEuler(Vec4 *angles, Mtx44 *m) {
    Mtx44 mt;
    Vec4 dir;

    __asm__ volatile(
        "lq $8, 0(%1)\n"
        "lq $9, 0x10(%1)\n"
        "lq $10, 0x20(%1)\n"
        "sq $8, 0(%0)\n"
        "sq $9, 0x10(%0)\n"
        "sq $10, 0x20(%0)\n"
        "sqc2 $vf0, 0x30(%0)\n"
        : : "r"(&mt), "r"(m) : "$8", "$9", "$10");
    Mtx_MulVec4(&dir, &mt, &gVu0AxisZW);
    Vec3_DirToEuler(angles, &dir);
}

/* void Mtx_SetTrans(Mtx44 *m, Vec4 *v): row 3 = v, all four words (128-bit move). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_SetTrans\n"
    ".type Mtx_SetTrans, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_SetTrans:\n"
    "    lq $8, 0x0($5)\n"
    "    jr $31\n"
    "    sq $8, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_SetTrans, . - Mtx_SetTrans\n"
);

/* void Mtx_Translate(Mtx44 *dst, Mtx44 *src, Vec4 *v): rows 0-2 copied, then row 3 = src row 3 with x, y, z += v. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_Translate\n"
    ".type Mtx_Translate, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_Translate:\n"
    "    lq $8, 0x0($5)\n"
    "    lq $9, 0x10($5)\n"
    "    lq $10, 0x20($5)\n"
    "    sq $8, 0x0($4)\n"
    "    sq $9, 0x10($4)\n"
    "    sq $10, 0x20($4)\n"
    "    lqc2 $vf4, 0x0($6)\n"
    "    lqc2 $vf5, 0x30($5)\n"
    "    vadd.xyz $vf5, $vf5, $vf4\n"
    "    jr $31\n"
    "    sqc2 $vf5, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_Translate, . - Mtx_Translate\n"
);

/* void Mtx_TranslateLocal(Mtx44 *dst, Mtx44 *src, Vec4 *v): rows 0-2 copied, row 3 = src * v (uses v.w). No callers. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_TranslateLocal\n"
    ".type Mtx_TranslateLocal, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_TranslateLocal:\n"
    "    lqc2 $vf8, 0x0($6)\n"
    "    lqc2 $vf4, 0x0($5)\n"
    "    lqc2 $vf5, 0x10($5)\n"
    "    lqc2 $vf6, 0x20($5)\n"
    "    lqc2 $vf7, 0x30($5)\n"
    "    vmulax.xyzw $ACC, $vf4, $vf8x\n"
    "    vmadday.xyzw $ACC, $vf5, $vf8y\n"
    "    vmaddaz.xyzw $ACC, $vf6, $vf8z\n"
    "    vmaddw.xyzw $vf7, $vf7, $vf8w\n"
    "    sqc2 $vf4, 0x0($4)\n"
    "    sqc2 $vf5, 0x10($4)\n"
    "    sqc2 $vf6, 0x20($4)\n"
    "    jr $31\n"
    "    sqc2 $vf7, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_TranslateLocal, . - Mtx_TranslateLocal\n"
);

/* void Mtx_Mul(Mtx44 *dst, Mtx44 *a, Mtx44 *b): dst.row[i] = a.row0 * b[i][0] + a.row1 * b[i][1] + a.row2 * b[i][2] +
 * a.row3 * b[i][3] (sceVu0MulMatrix). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_Mul\n"
    ".type Mtx_Mul, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_Mul:\n"
    "    lqc2 $vf4, 0x0($5)\n"
    "    lqc2 $vf5, 0x10($5)\n"
    "    lqc2 $vf6, 0x20($5)\n"
    "    lqc2 $vf7, 0x30($5)\n"
    "    lqc2 $vf8, 0x0($6)\n"
    "    lqc2 $vf9, 0x10($6)\n"
    "    lqc2 $vf10, 0x20($6)\n"
    "    lqc2 $vf11, 0x30($6)\n"
    "    vmulax.xyzw $ACC, $vf4, $vf8x\n"
    "    vmadday.xyzw $ACC, $vf5, $vf8y\n"
    "    vmaddaz.xyzw $ACC, $vf6, $vf8z\n"
    "    vmaddw.xyzw $vf8, $vf7, $vf8w\n"
    "    vmulax.xyzw $ACC, $vf4, $vf9x\n"
    "    vmadday.xyzw $ACC, $vf5, $vf9y\n"
    "    vmaddaz.xyzw $ACC, $vf6, $vf9z\n"
    "    vmaddw.xyzw $vf9, $vf7, $vf9w\n"
    "    vmulax.xyzw $ACC, $vf4, $vf10x\n"
    "    vmadday.xyzw $ACC, $vf5, $vf10y\n"
    "    vmaddaz.xyzw $ACC, $vf6, $vf10z\n"
    "    vmaddw.xyzw $vf10, $vf7, $vf10w\n"
    "    vmulax.xyzw $ACC, $vf4, $vf11x\n"
    "    vmadday.xyzw $ACC, $vf5, $vf11y\n"
    "    vmaddaz.xyzw $ACC, $vf6, $vf11z\n"
    "    vmaddw.xyzw $vf11, $vf7, $vf11w\n"
    "    sqc2 $vf8, 0x0($4)\n"
    "    sqc2 $vf9, 0x10($4)\n"
    "    sqc2 $vf10, 0x20($4)\n"
    "    jr $31\n"
    "    sqc2 $vf11, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_Mul, . - Mtx_Mul\n"
);

/* void Mtx_Copy(Mtx44 *dst, Mtx44 *src): four 128-bit moves. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_Copy\n"
    ".type Mtx_Copy, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_Copy:\n"
    "    lq $8, 0x0($5)\n"
    "    lq $9, 0x10($5)\n"
    "    lq $10, 0x20($5)\n"
    "    lq $11, 0x30($5)\n"
    "    sq $8, 0x0($4)\n"
    "    sq $9, 0x10($4)\n"
    "    sq $10, 0x20($4)\n"
    "    jr $31\n"
    "    sq $11, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_Copy, . - Mtx_Copy\n"
);

/* void Mtx_Transpose(Mtx44 *dst, Mtx44 *src). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_Transpose\n"
    ".type Mtx_Transpose, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_Transpose:\n"
    "    lq $8, 0x0($5)\n"
    "    lq $9, 0x10($5)\n"
    "    lq $10, 0x20($5)\n"
    "    lq $11, 0x30($5)\n"
    "    pextlw $12, $9, $8\n"
    "    pextuw $13, $9, $8\n"
    "    pextlw $14, $11, $10\n"
    "    pextuw $15, $11, $10\n"
    "    pcpyld $8, $14, $12\n"
    "    pcpyud $9, $12, $14\n"
    "    pcpyld $10, $15, $13\n"
    "    pcpyud $11, $13, $15\n"
    "    sq $8, 0x0($4)\n"
    "    sq $9, 0x10($4)\n"
    "    sq $10, 0x20($4)\n"
    "    jr $31\n"
    "    sq $11, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_Transpose, . - Mtx_Transpose\n"
);

/* void Mtx_InverseRT(Mtx44 *dst, Mtx44 *src): inverse of a rotation + translation matrix (sceVu0InversMatrix). */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_InverseRT\n"
    ".type Mtx_InverseRT, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_InverseRT:\n"
    "    lq $8, 0x0($5)\n"
    "    lq $9, 0x10($5)\n"
    "    lq $10, 0x20($5)\n"
    "    lqc2 $vf4, 0x30($5)\n"
    "    vmove.xyzw $vf5, $vf4\n"
    "    vmove.xyz $vf4, $vf0\n"
    "    qmfc2 $11, $vf4\n"
    "    pextlw $12, $9, $8\n"
    "    pextuw $13, $9, $8\n"
    "    pextlw $14, $11, $10\n"
    "    pextuw $15, $11, $10\n"
    "    pcpyld $8, $14, $12\n"
    "    pcpyud $9, $12, $14\n"
    "    pcpyld $10, $15, $13\n"
    "    qmtc2 $8, $vf6\n"
    "    qmtc2 $9, $vf7\n"
    "    qmtc2 $10, $vf8\n"
    "    vmulax.xyz $ACC, $vf6, $vf5x\n"
    "    vmadday.xyz $ACC, $vf7, $vf5y\n"
    "    vmaddz.xyz $vf4, $vf8, $vf5z\n"
    "    vsub.xyz $vf4, $vf0, $vf4\n"
    "    sq $8, 0x0($4)\n"
    "    sq $9, 0x10($4)\n"
    "    sq $10, 0x20($4)\n"
    "    jr $31\n"
    "    sqc2 $vf4, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_InverseRT, . - Mtx_InverseRT\n"
);

/* void Mtx_RotateZ(Mtx44 *dst, Mtx44 *src, f32 angle): dst = src * Rz. Keeps $ra in $a2 around Vu0_SinCos. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_RotateZ\n"
    ".type Mtx_RotateZ, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_RotateZ:\n"
    "    daddu $6, $31, $zero\n"
    "    jal Vu0_SinCos\n"
    "    nop\n"
    "    daddu $31, $6, $zero\n"
    "    lqc2 $vf4, 0x0($5)\n"
    "    lqc2 $vf5, 0x10($5)\n"
    "    lqc2 $vf6, 0x20($5)\n"
    "    lqc2 $vf7, 0x30($5)\n"
    "    vsub.zw $vf8, $vf0, $vf0\n"
    "    vaddy.x $vf8, $vf0, $vf12y\n"
    "    vaddx.y $vf8, $vf0, $vf12x\n"
    "    vsub.zw $vf9, $vf0, $vf0\n"
    "    vsubx.x $vf9, $vf0, $vf12x\n"
    "    vaddy.y $vf9, $vf0, $vf12y\n"
    "    vmulax.xyzw $ACC, $vf8, $vf4x\n"
    "    vmadday.xyzw $ACC, $vf9, $vf4y\n"
    "    vmaddaz.xyzw $ACC, $vf1, $vf4z\n"
    "    vmaddw.xyzw $vf4, $vf0, $vf4w\n"
    "    vmulax.xyzw $ACC, $vf8, $vf5x\n"
    "    vmadday.xyzw $ACC, $vf9, $vf5y\n"
    "    vmaddaz.xyzw $ACC, $vf1, $vf5z\n"
    "    vmaddw.xyzw $vf5, $vf0, $vf5w\n"
    "    vmulax.xyzw $ACC, $vf8, $vf6x\n"
    "    vmadday.xyzw $ACC, $vf9, $vf6y\n"
    "    vmaddaz.xyzw $ACC, $vf1, $vf6z\n"
    "    vmaddw.xyzw $vf6, $vf0, $vf6w\n"
    "    vmulax.xyzw $ACC, $vf8, $vf7x\n"
    "    vmadday.xyzw $ACC, $vf9, $vf7y\n"
    "    vmaddaz.xyzw $ACC, $vf1, $vf7z\n"
    "    vmaddw.xyzw $vf7, $vf0, $vf7w\n"
    "    sqc2 $vf4, 0x0($4)\n"
    "    sqc2 $vf5, 0x10($4)\n"
    "    sqc2 $vf6, 0x20($4)\n"
    "    jr $31\n"
    "    sqc2 $vf7, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_RotateZ, . - Mtx_RotateZ\n"
);

/* void Mtx_RotateX(Mtx44 *dst, Mtx44 *src, f32 angle): dst = src * Rx. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_RotateX\n"
    ".type Mtx_RotateX, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_RotateX:\n"
    "    daddu $6, $31, $zero\n"
    "    jal Vu0_SinCos\n"
    "    nop\n"
    "    daddu $31, $6, $zero\n"
    "    lqc2 $vf4, 0x0($5)\n"
    "    lqc2 $vf5, 0x10($5)\n"
    "    lqc2 $vf6, 0x20($5)\n"
    "    lqc2 $vf7, 0x30($5)\n"
    "    vsub.xw $vf8, $vf0, $vf0\n"
    "    vaddy.y $vf8, $vf0, $vf12y\n"
    "    vaddx.z $vf8, $vf0, $vf12x\n"
    "    vsub.xw $vf9, $vf0, $vf0\n"
    "    vsubx.y $vf9, $vf0, $vf12x\n"
    "    vaddy.z $vf9, $vf0, $vf12y\n"
    "    vmulax.xyzw $ACC, $vf3, $vf4x\n"
    "    vmadday.xyzw $ACC, $vf8, $vf4y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf4z\n"
    "    vmaddw.xyzw $vf4, $vf0, $vf4w\n"
    "    vmulax.xyzw $ACC, $vf3, $vf5x\n"
    "    vmadday.xyzw $ACC, $vf8, $vf5y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf5z\n"
    "    vmaddw.xyzw $vf5, $vf0, $vf5w\n"
    "    vmulax.xyzw $ACC, $vf3, $vf6x\n"
    "    vmadday.xyzw $ACC, $vf8, $vf6y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf6z\n"
    "    vmaddw.xyzw $vf6, $vf0, $vf6w\n"
    "    vmulax.xyzw $ACC, $vf3, $vf7x\n"
    "    vmadday.xyzw $ACC, $vf8, $vf7y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf7z\n"
    "    vmaddw.xyzw $vf7, $vf0, $vf7w\n"
    "    sqc2 $vf4, 0x0($4)\n"
    "    sqc2 $vf5, 0x10($4)\n"
    "    sqc2 $vf6, 0x20($4)\n"
    "    jr $31\n"
    "    sqc2 $vf7, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_RotateX, . - Mtx_RotateX\n"
);

/* void Mtx_RotateY(Mtx44 *dst, Mtx44 *src, f32 angle): dst = src * Ry. */
__asm__(
    ".text\n"
    ".align 3\n"
    ".globl Mtx_RotateY\n"
    ".type Mtx_RotateY, @function\n"
    ".set push\n"
    ".set noreorder\n"
    "Mtx_RotateY:\n"
    "    daddu $6, $31, $zero\n"
    "    jal Vu0_SinCos\n"
    "    nop\n"
    "    daddu $31, $6, $zero\n"
    "    lqc2 $vf4, 0x0($5)\n"
    "    lqc2 $vf5, 0x10($5)\n"
    "    lqc2 $vf6, 0x20($5)\n"
    "    lqc2 $vf7, 0x30($5)\n"
    "    vsub.yw $vf8, $vf0, $vf0\n"
    "    vaddy.x $vf8, $vf0, $vf12y\n"
    "    vsubx.z $vf8, $vf0, $vf12x\n"
    "    vsub.yw $vf9, $vf0, $vf0\n"
    "    vaddx.x $vf9, $vf0, $vf12x\n"
    "    vaddy.z $vf9, $vf0, $vf12y\n"
    "    vmulax.xyzw $ACC, $vf8, $vf4x\n"
    "    vmadday.xyzw $ACC, $vf2, $vf4y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf4z\n"
    "    vmaddw.xyzw $vf4, $vf0, $vf4w\n"
    "    vmulax.xyzw $ACC, $vf8, $vf5x\n"
    "    vmadday.xyzw $ACC, $vf2, $vf5y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf5z\n"
    "    vmaddw.xyzw $vf5, $vf0, $vf5w\n"
    "    vmulax.xyzw $ACC, $vf8, $vf6x\n"
    "    vmadday.xyzw $ACC, $vf2, $vf6y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf6z\n"
    "    vmaddw.xyzw $vf6, $vf0, $vf6w\n"
    "    vmulax.xyzw $ACC, $vf8, $vf7x\n"
    "    vmadday.xyzw $ACC, $vf2, $vf7y\n"
    "    vmaddaz.xyzw $ACC, $vf9, $vf7z\n"
    "    vmaddw.xyzw $vf7, $vf0, $vf7w\n"
    "    sqc2 $vf4, 0x0($4)\n"
    "    sqc2 $vf5, 0x10($4)\n"
    "    sqc2 $vf6, 0x20($4)\n"
    "    jr $31\n"
    "    sqc2 $vf7, 0x30($4)\n"
    ".set pop\n"
    ".size Mtx_RotateY, . - Mtx_RotateY\n"
);
